name: ci
on:
  push:
    branches-ignore:
      - "master"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17
      - env:
          GHOPS_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install
      - run: node packages/ghops-action/index.js
