name: ghops

on: [workflow_dispatch]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17
          registry-url: https://npm.pkg.github.com/
          scope: "@my-devops-playground"
      - run: "npm i -g @my-devops-playground/ghops-action@1.0.4 && ghops --help"
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
