name: ghops

on: [workflow_dispatch]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17
          registry-url: https://npm.pkg.github.com/
          scope: "@my-devops-playground"
      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
      - run: "npm i -g @my-devops-playground/ghops-action"
      - run: "ghops --token ${{ secrets.GH_TOKEN }} --config ghops.json"
