name: publishing

on:
  push:
    branches:
      - "master"

jobs:
  publish-ghp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node: 16.17
          registry-uri: https://npm.pkg.github.com
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}