name: publishing

on:
  push:
    branches:
      - "master"

jobs:
  publish-ghp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17
          registry-url: https://npm.pkg.github.com/
          scope: '@my-devops-playground'
      - run: yarn install
      - run: yarn publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}